### ISSUE TITLE
Windows 11 Pro v21H2 - Not working

### ISSUE THREAD

**Issue by winware2000** [Stratium/Google-Drive-for-Desktop-Integration#2]
Hello,

It looks that it is **NOT** working on the official version of Windows 11 Pro (21H2).
Can anyone confirm this?

Sergios

**Comment by Stratium** [comment]
Hi @winware2000 

I can confirm that this is still working on Windows 11 Pro 21H2, as this is what my main machine is currently running.
Have you followed the instructions in the readme correctly? The current version of Google Drive for Desktop is 52.0.6.0, which means for the latest install you would need to edit the registry file to show the new file path to the Google Drive executable.

On my machine, this is currently C:\Program Files\Google\Drive File Stream\52.0.6.0\GoogleDriveFS.exe - meaning you would need to make the following edits:

`[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}\DefaultIcon]
@="C:\Program Files\Google\Drive File Stream\52.0.6.0\GoogleDriveFS.exe,0"`

`[HKEY_CURRENT_USER\Software\Classes\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}\DefaultIcon]
@="C:\Program Files\Google\Drive File Stream\52.0.6.0\GoogleDriveFS.exe,0"`

Kind regards,
Stratium
