### ISSUE TITLE
Multiple Google Drive A/C's

### ISSUE THREAD

**Issue by jasubhai** [Stratium/Google-Drive-for-Desktop-Integration#3]
Hi,

I have multiple Google Drive a/c's synced on my desktop. 

Please could you let me know as to how each of them can be added? I could successfully add 1 as per your instructions. 

Thank You
Jasu

**Comment by Stratium** [comment]
Hi Jasubhai,

This isn't something that this registry edit supports natively.
I don't have two Google accounts to test, but I assume this could be technically done if Google Drive creates separate registry entries for the separate accounts?

For example, your first account may come under:
`[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}\Instance\InitPropertyBag]
"Attributes"=dword:00000011
"TargetFolderPath"="G:\\My Drive"`

but your second account may come under
`[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{NEW CLSID}\Instance\InitPropertyBag]
"Attributes"=dword:00000011
"TargetFolderPath"="F:\\My Drive"`

You'll have to play around and see if this is how they have implemented it, unfortunately, I don't plan to maintain this repository any further than keeping it running with any bug fixes for new versions.

Kind regards,
Stratium
