### ISSUE TITLE
[Question] How do I change the Name?

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Stratium/Google-Drive-for-Desktop-Integration#4]
I'm currently wanting to change the name of the Drive. But am not sure how. Is there an area in the `.reg` I can change?

**Comment by Stratium** [comment]
I've played around with the values in the registry and couldn't find which values dictate the name of the shortcut.
Modifying [HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}] causes the drive to stop linking to Google, while [HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}] seems to have no effect.

Unfortunately, it looks like this is handled elsewhere?
