### ISSUE TITLE
iCloud Drive

### ISSUE THREAD

**Issue by mlynekj** [Stratium/Google-Drive-for-Desktop-Integration#5]
Hi,

I love this tweak, been using the original version since the beginning and now after google changed its windows application this has been a lifesaver. 

However now i have issues with iCloud drive, could this, by any chance, be altered to do the same thing with iCloud Drive? I can't figure it out.

Thanks in advance.

**Comment by Stratium** [comment]
Hi Yakubcze,

This shouldn't have any conflicts with the iCloud drive as this doesn't touch any registry values which are in use with iCloud.
It might be worth running the uninstall registry file and seeing if iCloud functionality returns, however.
