### ISSUE TITLE
Icon In File Explorer

### ISSUE THREAD

**Issue by scottie612** [Stratium/Google-Drive-for-Desktop-Integration#6]
So instead of the google drive icon in the file explorer, it looks like a folder. The items are in there correctly, just wondering where or how I can update it.

Thanks

**Comment by Stratium** [comment]
Hi @scottie612 

You need to change the registry file in two places to point to the current location of GoogleDriveFS as per the installation instructions.

As of today, the latest version of Google Drive File Stream on my PC is 55.0.3.0, so I would edit my registry file to read:

```
[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}\DefaultIcon]
@="C:\\Program Files\\Google\\Drive File Stream\\55.0.3.0\\GoogleDriveFS.exe,0"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}\DefaultIcon]
@="C:\\Program Files\\Google\\Drive File Stream\\55.0.3.0\\GoogleDriveFS.exe,0"
```

I guess technically if Google is removing old versions of File Stream when it updates it might break the shortcut to this icon.
A more permanent fix would be to create a copy of GoogleDriveFS.exe in a safe location, and point these two registry files there instead - for example:

```
[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}\DefaultIcon]
@="C:\\BACKUP\\GoogleDriveFS.exe,0"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{CFE8B367-77A7-41D7-9C90-75D16D7DC6B6}\DefaultIcon]
@="C:\\BACKUP\\GoogleDriveFS.exe,0"
```

I've updated the readme to clarify this workaround to other users.

I hope this helps,
Stratium
